name: Build Check - All LTS Kernels

permissions:
  contents: write
  actions: write

on:
  push:
  workflow_dispatch:

jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        kernel_config:
          # Android 15 - Kernel 6.6 LTS
          - android_version: "android15"
            kernel_version: "6.6"
            sub_level: "30"
            os_patch_level: "2024-08"

    name: Build Check
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.kernel_config.android_version }}
      kernel_version: ${{ matrix.kernel_config.kernel_version }}
      sub_level: ${{ matrix.kernel_config.sub_level }}
      os_patch_level: ${{ matrix.kernel_config.os_patch_level }}
